### ISSUE TITLE
Extract Factory Pattern

### ISSUE THREAD

**Issue by dsager** [Devex/article_json#79]
Different base classes implement a factory pattern to create sub classes dynamically. Check if this can  be extracted into a module and shared among all base classes...

**Comment by nicolas-fricke** [comment]
For the HTML and AMP exporters this has been done in PR #108 :)

@dsager are there more instances of reusable code you think would be worthwhile extracting?

**Comment by dsager** [comment]
@nicolas-fricke The classes `ArticleJSON::Import::GoogleDoc::HTML::Parser` and `ArticleJSON::Elements::Base` both have a similar `type -> class` mapping. Both use the same or a similar pattern, the parser is a bit different though, so not sure if it would make sense to use something re-usable here...
